apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-dependencies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shmueliitay/retail-store-sample-app.git//src/dependencies/chart?ref=main'
    targetRevision: main
    path: src/dependencies/chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: retail-store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

